# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-04 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontak', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nama_lenkap',
            new_name='nama_lengkap',
        ),
    ]
